### ISSUE TITLE
Error when require()'ing through Browserify

### ISSUE THREAD

**Issue by jazzido** [alexandersimoes/d3plus#315]
Hey,

I'm `require()`ing `d3plus` on my main JS file, and getting this error when running `browserify`:

```
Error: Cannot find module './array/comparator.coffee' from '/Users/manuel/Work/opus-frontend/v1.0/node_modules/d3plus'
  at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
  at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
  at Object.oncomplete (fs.js:107:15)
```

**Comment by davelandry** [comment]
How are you installing d3plus?

**Comment by jazzido** [comment]
`npm install --save d3plus`


--
Manuel Aristarán
http://jazzido.com

**Comment by davelandry** [comment]
@jazzido, can you try this for a local fix:
* open `package.json` in the root of node_modules/d3plus
* change line 5 to say: `"main": "src/init.coffee",`

If that fixes it, I will change that for the next npm release

**Comment by davelandry** [comment]
@jazzido, have you had any luck with this?

**Comment by lsapan** [comment]
@davelandry I just tried installing d3plus from npm as well (looks like you've already made the change on line 5) and it still fails to compile. Here's the error:

```
SyntaxError: Unexpected character '#' (2:0) while parsing /..../project/node_modules/d3plus/src/init.coffee while parsing file: /..../project/node_modules/d3plus/src/init.coffee
    at DestroyableTransform.end [as _flush] (/..../project/node_modules/browserify/node_modules/insert-module-globals/index.js:73:21)
    at DestroyableTransform.<anonymous> (/..../project/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
    at prefinish (/..../project/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:450:12)
    at finishMaybe (/..../project/node_modules/browserify/node_modules/readable-stream/loib/_stream_writable.js:458:7)
    at endWritable (/..../project/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at DestroyableTransform.Writable.end (/..../project/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DestroyableTransform.onend (/..../project/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DestroyableTransform.g (events.js:199:16)
```

I've also tried just manually downloading it and requiring it, but `require('d3plus')` then yields an empty object.

**Comment by davelandry** [comment]
Does #353 solve this issue?

**Comment by danieldram** [comment]
Same issue here..  Is there a fork or another repository that supports browserify?

**Comment by davelandry** [comment]
From @danieldram in #388:

>angular.js:12477 ReferenceError: d3 is not defined
at Object.51 (scale.coffee:2)
at s (_prelude.js:1)
at _prelude.js:1
at Object.50../scale.coffee (random.coffee:1)
at s (_prelude.js:1)
at _prelude.js:1
at Object.66.../../color/random.coffee (color.coffee:2)
at s (_prelude.js:1)
at _prelude.js:1
at Object.68../color.coffee (sort.coffee:2)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$apply @ angular.js:16094bootstrapApply @ angular.js:1660invoke @ angular.js:4478doBootstrap @ angular.js:1658bootstrap @ angular.js:1678angularInit @ angular.js:1572(anonymous function) @ angular.js:28899trigger @ angular.js:3024eventHandler @ angular.js:3298

Would love some help on this one. Could be as simple as an issue with the package.json, or could be a problem with how we use browserify internally:
https://github.com/alexandersimoes/d3plus/blob/master/gulp/compile.coffee
