### ISSUE TITLE
Nodejs Issues

### ISSUE THREAD

**Issue by ncgonz** [alexandersimoes/d3plus#375]
I'm not sure if I'm doing something wrong, but when I install this package in nodejs, I end up getting an Illegal character issue.  I found issue #244 and used the solution from that to fix it locally, but then met with a entirely new slew of errors, with d3 being undefined (I do require d3 first) and window being undefined.  

Should the expectation be that this not work in node?  I'm using d3, jsdom and canvg to render my d3 visualizations as images on the server, and this is the one component that works well in the browser but doesn't seem to work in the node environment.

**Comment by davelandry** [comment]
Can you outline the local environment fix you did?

Also, can you copy/paste the exact errors you are seeing?

**Comment by ncgonz** [comment]
Sure.  for the Illegal Token issue, the error was:

`SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Nathan\Projects\d3test\js\gradientBubble.js:5:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)`

Which based on issue #244 I found could be fixed by changing line 5 in package.json from `init.coffee` to `d3plus.js`.

After that I got the following:

`ReferenceError: d3 is not defined
    at Object.__dirname.49 (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:10541:18)
    at s (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:1:316)
    at C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:1:367
    at Object.__dirname.48../scale.coffee (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:10530:16)
    at s (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:1:316)
    at C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:1:367
    at Object.__dirname.64.../../color/random.coffee (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:12000:15)
    at s (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:1:316)
    at C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:1:367
    at Object.__dirname.66../color.coffee (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:12297:14)`

and then, after requiring d3 in the d3plus.js file i got:

`ReferenceError: window is not defined
    at Object.__dirname.44 (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:10480:37)
    at s (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:254)
    at C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:305
    at Object.__dirname.40../ie.js (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:10392:9)
    at s (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:254)
    at C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:305
    at Object.__dirname.162../array/comparator.coffee (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:18532:12)
    at s (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:254)
    at e (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:425)
    at Object.<anonymous> (C:\Users\Nathan\Projects\d3test\node_modules\d3plus\d3plus.js:3:443)`

and then I gave up.

**Comment by davelandry** [comment]
If you change line 5 of package.json to ```d3plus.full.js``` you won't have to additionally load d3. I'll update the repo with this change.

The ```window is not defined``` error is probably occuring because d3plus is a client-side library that relies on being rendered in the browser. It calls for the browser window in multiple places in order to render things properly.

How are you using d3plus?

**Comment by ncgonz** [comment]
I'm rendering svg's on the server using d3 and jsdom.  I'm then converting them to canvas using canvg, and from there streaming them to the client as a png using toDataURL.  All the other pieces seem to be working, but when I introduce d3plus there are issues.  I'm really only using d3plus for the text sizing and alignment within containers.

**Comment by davelandry** [comment]
The majority of the text sizing functions rely on rendering the text to the page in the browser and performing calculations based on the rendered size. You'll probably need to run some sort of browser (selenium?) on the server in order to use D3plus on the server.

**Comment by ncgonz** [comment]
Thanks for taking the time to reply.  I have a (virtual) window object.  jsdom has a complete DOM.  I'm able to do (comparatively rudimentary) text sizing and alignment on my own using it.  The problem is that I can't supply my window to your library, it just assumes there will be a global window always available.  I think a lot of this could be curtailed by allowing for a window object to be supplied.  I'm obviously a pretty narrow use case, so I don't expect you to make this change for me, but I'm also not a coffeescript guy, so I'd love a hint as to where jump in so i can do this at least locally.

**Comment by alexandraorth** [comment]
Just to follow up–– I'd like to second this feature request as I am having the exact same issue as above. Thanks for the library, it's been amazingly useful!

**Comment by ncgonz** [comment]
@alexandraorth, turns out he is right, based on the way that getComputedTextLength works, the svg has to be rendered to an actual dom.  jsdom doesn't seem to implement that properly...  or at all, that method doesn't exist on svg text elements.  I'm in the middle of trying to reimplement it by drawing the text to a canvas object using node-canvas and then measuring it that way.  If i get anything figured out I'll let you know.

**Comment by davelandry** [comment]
Have you guys seen [Electron](http://electron.atom.io/)? I'm using it for some browser tests and it's pretty slick. It's based on Chrome, so I would assume it has great SVG support.

**Comment by ncgonz** [comment]
Yeah,  electron is pretty awesome.  We build our desktop app using it.  Unfortunately my use case is that I have some pretty complicated charts and data visualizations that I'd like to have  look the same across web, desktop and mobile.  Web and desktop (electron) work like a champ, because they're both browsers.  Mobile is a little more difficult, and we're looking to solve that by rendering svg on the server.  We're then converting them to pngs and streaming them down to all of the clients.  Just doesn't seem like d3plus is going to work for that purpose for us, based on the hard requirements of a real dom.  It's an awesome library, and I don't look forward to figuring out how to reimplement the pieces I have to have.
