### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#677]
here's my npm log after running `npm run-script build`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle d3plus@2.0.0-alpha.17~prebuild: d3plus@2.0.0-alpha.17
6 info lifecycle d3plus@2.0.0-alpha.17~build: d3plus@2.0.0-alpha.17
7 verbose lifecycle d3plus@2.0.0-alpha.17~build: unsafe-perm in lifecycle true
8 verbose lifecycle d3plus@2.0.0-alpha.17~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pacha/github/d3plus2-source/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle d3plus@2.0.0-alpha.17~build: CWD: /home/pacha/github/d3plus2-source
10 silly lifecycle d3plus@2.0.0-alpha.17~build: Args: [ '-c', 'npm run pretest && d3plus-build' ]
11 silly lifecycle d3plus@2.0.0-alpha.17~build: Returned: code: 1  signal: null
12 info lifecycle d3plus@2.0.0-alpha.17~build: Failed to exec build script
13 verbose stack Error: d3plus@2.0.0-alpha.17 build: `npm run pretest && d3plus-build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid d3plus@2.0.0-alpha.17
15 verbose cwd /home/pacha/github/d3plus2-source
16 verbose Linux 4.15.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run-script" "build"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error d3plus@2.0.0-alpha.17 build: `npm run pretest && d3plus-build`
22 error Exit status 1
23 error Failed at the d3plus@2.0.0-alpha.17 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pachamaltese** [comment]
@davelandry as of 02.11.2019 I couldn't build d3plus on Ubuntu or CentOS
I updated some packages with critical updates and it worked

since I didn't fork but I just did a clone with depth 1, you can check here:
https://github.com/pachamaltese/d3plus2/blob/source/index.js

**Comment by davelandry** [comment]
@pachamaltese take a look at the latest build and let me know if you're still having issues. I updated a lot of dependencies.

**Comment by pachamaltese** [comment]
@davelandry it works ok with these last changes, last nght it worked after some minor tweaking
thanks a lot Dave !! I'm opening a separate issue w.r to this build
